Added logOff component
michalvankodev/ness-inter-poll pull request #23
Opened 2018-05-14 15:00 UTC by LukasOscipovsky

Added logOff component

2018-05-18 13:24 UTC, michalvankodev requested changes

2018-05-18 13:24 UTC, michalvankodev commented on nesspoll/src/components/LogOff.tsx
> +export class LogOff extends React.Component<any, any> {
Doesn't make sense to use TypeScript if everything is casted to any

2018-05-18 13:24 UTC, michalvankodev commented on nesspoll/src/styles/components/log_off.scss
> +    width: 40px !important;
Don't use !important unless necessary (rewriting libraries etc.) You should always be able to create a selector with priority which doesn't require using !important

2018-05-20 08:50 UTC, LukasOscipovsky commented on nesspoll/src/styles/components/log_off.scss
> +    width: 40px !important;
saw that in close component, I reuse it but will look at it further

2018-05-28 11:02 UTC, merged